name : Workflow uses actions

on: [push]

jobs:
  checkoutaction:
    runs-on: windows-latest
    steps:
      - name: call checkout action 
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      
