name : Workflow uses actions

on: [delete]

jobs:
  checkoutaction:
    runs-on: ubuntu-latest
    steps:
      - name: call checkout action
        uses: actions/checkout@v1
      - name: list files after checkout
        run: echo $GITHUB_REPOSITORY
      
