name: Triggers on PR
on:
  schedule:
    - cron: '* * * * *'
  pull_request:
    types: [opened, closed]


  

jobs:
  job1-run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello world"

      - name: Step 2
        run: echo "This is a cron step"

