name: Triggers on PR
on:
  pull_request:
    types: [opened, closed]
  schedule:
    - cron: '* * * * *'

  

jobs:
  job1-run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"

