name: "First test action"

on: [push]

jobs:
  job1-run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name : multistep
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print (platform.processor())
        shell: python


  job2-run-shell-command:
    runs-on: windows-latest
    needs: [job1-run-shell-command]
    steps:
      - name: echo a string
        run: echo "Hello world with vscode"